log:
    slack:
        channelId: ${DEV_SLACK_CHANNEL_ID}
        token: ${SLACK_BOT_TOKEN:xoxb-5851331701847-6039190986864-bndCAj9ytfPM6VtC21TSrUtd}
        botName: ${SLACK_BOT_NAME:DangleServer-ErrorNotiBot}
        botIcon: ${SLACK_BOT_ICON::ok_twitch:}
    dashboard:
        url: ${DEV_LOG_DASHBOARD_URL}
