spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: local
  transaction:
    default-timeout: 4
  config:
    import:
      - logging.yml
      - application-actuator.yml
      - oauth/application-oauth-${spring.profiles.active}.yml
      - application-log-${spring.profiles.active}.yml
      - application-client-${spring.profiles.active}.yml
      - application-storage-${spring.profiles.active}.yml
      - application-redis-${spring.profiles.active}.yml
      - application-mail-${spring.profiles.active}.yml
      - 'aws-parameterstore:'
springdoc:
  swagger-ui:
    path: /swagger

jwt:
    access:
        expire: ${ACCESS_TOKEN_EXPIRE:86400000} # 1 day
        secret: ${ACCESS_TOKEN_SECRET:5f95a5f5c5b5a5a5958f8f7f7e7e7d7d7c6b6a696867666564636261605f}
    refresh:
        expire: ${REFRESH_TOKEN_EXPIRE:604800000} # 1 week
        secret: ${REFRESH_TOKEN_SECRET:5f95a5f5c5b5a5a5958f8f7f7e7e7d7d7c6b6a696867666564636261605f}
    auth:
        expire: ${AUTH_TOKEN_EXPIRE:300000} # 5 min
        secret: ${AUTH_TOKEN_SECRET:5f95a5f5c5b5a5a5958f8f7f7e7e7d7d7c6b6a696867666564636261605f}

aws:
    paramstore:
        enabled: true
        prefix: /dangle-parameter-store
        name: legacy-api
        profile-separator: _
        fail-fast: true
