# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: api-ci-dev

on:
    pull_request:
        branches: [ feat/YW2-134 ]
        paths:
            - 'src/app/api/**'
            - 'src/domain/auth/**'
            - 'src/domain/volunteer/**'
            - 'src/domain/shelter/**'
            - 'src/domain/volunteerEvent/**'
            - 'src/infrastructure/client/**'
            - 'src/infrastructure/storage/**'
            - 'src/infrastructure/redis/**'
            - 'src/support/logger/**'
            - 'src/support/common/**'
            - 'src/support/lock/**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: xt0rted/pull-request-comment-branch@v1
              id: comment-branch
            - uses: actions/checkout@v2
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                    java-version: '17'
                    distribution: 'temurin'
            - name: Cache Gradle
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Lint-Check
              id: lintCheck
              run: ./gradlew :api:ktlintCheck
            - name: API Test
              id: apiTest
              run: ./gradlew :api:test
            - name: Storage Test
              id: storageTest
              run: ./gradlew :storage:test
            - name: Lock Test
              id: lockTest
              run: ./gradlew :lock:test

            - name: Comment when Lint was Failed
              uses: peter-evans/create-or-update-comment@v2
              if: failure() && steps.lintCheck.outcome == 'failure'
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  body: |
                      :x: Lint 실패
            - name: Comment When UnitTest Was Failed
              uses: peter-evans/create-or-update-comment@v2
              if: failure() && (steps.apiTest.outcome == 'failure' || steps.storageTest.outcome == 'failure')
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  body: |
                      :x: Test 실패.
            - name: Comment When All Step Was Passed
              uses: peter-evans/create-or-update-comment@v2
              if: success()
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  body: |
                      :white_check_mark: CI 통과
